#pragma once
#define DEFAULT_WIDTH 800.f
#define DEFAULT_HEIGHT 600.f

#define HORIZONTAL_MARGIN 110.f
#define HORIZONTAL_START_POSITION 70.f

#define VERTICAL_MARGIN 120.f
#define VERTICAL_START_POSITION 90.f

#define BAR_HEIGHT 720.f
#define BAR_DURATION 0.2f
#define START_FINISH_BAR_DURATION 0.3f

#define DEFAULT_POSITION 240.f
#define DEFAULT_MOVE_DURATION 1.f

#define CENTER_LINE_ITEM 2

#define ZERO 0.f
